import type { IconType } from "react-icons";
import {
  SiAndroidstudio,
  SiAngular,
  SiAppstore,
  SiBootstrap,
  SiCpanel,
  SiCss,
  SiDocker,
  SiExpress,
  SiExpo,
  SiFigma,
  SiFlutter,
  SiGit,
  SiGithub,
  SiGoogleanalytics,
  SiGoogle,
  SiGoogleplay,
  SiGoogletagmanager,
  SiHtml5,
  SiJavascript,
  SiJson,
  SiKubernetes,
  SiPagespeedinsights,
  SiSemrush,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiRedis,
  SiRailway,
  SiReact,
  SiRedux,
  SiRender,
  SiSass,
  SiShadcnui,
  SiSqlite,
  SiSwagger,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVuedotjs,
} from "react-icons/si";
import { DiMsqlServer } from "react-icons/di";
import {
  TbBrandReactNative,
  TbApi,
  TbCloudComputing,
  TbComponents,
} from "react-icons/tb";
import { ShopierIcon } from "./ShopierIcon";
import { ZustandIcon } from "./ZustandIcon";

export interface TechItem {
  name: string;
  icon: IconType;
  tooltip?: string;
}

export const techItems: TechItem[] = [
  { name: "HTML", icon: SiHtml5 },
  { name: "CSS", icon: SiCss },
  { name: "Sass & SCSS", icon: SiSass },
  { name: "TypeScript", icon: SiTypescript },
  { name: "JavaScript", icon: SiJavascript },
  { name: "Tailwind CSS", icon: SiTailwindcss },
  { name: "Bootstrap", icon: SiBootstrap },
  { name: "Next.js", icon: SiNextdotjs },
  { name: "React", icon: SiReact },
  { name: "Angular", icon: SiAngular },
  { name: "Vue", icon: SiVuedotjs },
  { name: "Redux", icon: SiRedux },
  { name: "Zustand", icon: ZustandIcon },
  { name: "Shadcn", icon: SiShadcnui },
  {
    name: "UI",
    icon: TbComponents,
    tooltip: "UI(Shadcn, Material, ...)",
  },
  { name: "React Native", icon: TbBrandReactNative },
  { name: "Flutter", icon: SiFlutter },
  { name: "Expo", icon: SiExpo },
  { name: "Android Studio", icon: SiAndroidstudio },
  { name: "Node.js", icon: SiNodedotjs },
  { name: "Express.js", icon: SiExpress },
  { name: "REST API", icon: TbApi },
  { name: "Prisma", icon: SiPrisma },
  { name: "MySQL", icon: SiMysql },
  { name: "MongoDB", icon: SiMongodb },
  { name: "PostgreSQL", icon: SiPostgresql },
  { name: "MSSQL", icon: DiMsqlServer },
  { name: "SQLite", icon: SiSqlite },
  { name: "Vercel", icon: SiVercel },
  { name: "Railway", icon: SiRailway },
  { name: "Shopier", icon: ShopierIcon },
  { name: "CollectAPI", icon: TbCloudComputing },
  { name: "Render", icon: SiRender },
  { name: "cPanel", icon: SiCpanel },
  { name: "Figma", icon: SiFigma },
  { name: "Git", icon: SiGit },
  { name: "GitHub", icon: SiGithub },
  { name: "Postman", icon: SiPostman },
  { name: "Redis", icon: SiRedis },
  { name: "Docker", icon: SiDocker },
  { name: "Kubernetes", icon: SiKubernetes },
  { name: "Swagger / OpenAPI", icon: SiSwagger },
  { name: "Google Search", icon: SiGoogle },
  { name: "Google Analytics", icon: SiGoogleanalytics },
  { name: "PageSpeed Insights", icon: SiPagespeedinsights },
  { name: "Google Tag Manager", icon: SiGoogletagmanager },
  { name: "Semrush", icon: SiSemrush },
  { name: "JSON-LD", icon: SiJson },
  { name: "App Store", icon: SiAppstore },
  { name: "Google Play", icon: SiGoogleplay },
];

export const techItemCount = techItems.length;
