import type { IconType } from "react-icons";
import {
  SiAndroidstudio,
  SiAppstore,
  SiBootstrap,
  SiCpanel,
  SiCss,
  SiExpress,
  SiExpo,
  SiFigma,
  SiFlutter,
  SiGit,
  SiGithub,
  SiGoogleanalytics,
  SiGoogle,
  SiGoogleplay,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiRailway,
  SiReact,
  SiRedux,
  SiRender,
  SiShadcnui,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
} from "react-icons/si";
import { TbBrandReactNative, TbApi } from "react-icons/tb";

export interface TechItem {
  name: string;
  icon: IconType;
}

export const techItems: TechItem[] = [
  { name: "HTML", icon: SiHtml5 },
  { name: "CSS", icon: SiCss },
  { name: "TypeScript", icon: SiTypescript },
  { name: "JavaScript", icon: SiJavascript },
  { name: "Tailwind CSS", icon: SiTailwindcss },
  { name: "Bootstrap", icon: SiBootstrap },
  { name: "Next.js", icon: SiNextdotjs },
  { name: "React", icon: SiReact },
  { name: "Redux", icon: SiRedux },
  { name: "shadcn/ui", icon: SiShadcnui },
  { name: "React Native", icon: TbBrandReactNative },
  { name: "Flutter", icon: SiFlutter },
  { name: "Expo", icon: SiExpo },
  { name: "Android Studio", icon: SiAndroidstudio },
  { name: "Node.js", icon: SiNodedotjs },
  { name: "Express.js", icon: SiExpress },
  { name: "REST API", icon: TbApi },
  { name: "Prisma", icon: SiPrisma },
  { name: "MySQL", icon: SiMysql },
  { name: "MongoDB", icon: SiMongodb },
  { name: "PostgreSQL", icon: SiPostgresql },
  { name: "Vercel", icon: SiVercel },
  { name: "Railway", icon: SiRailway },
  { name: "Render", icon: SiRender },
  { name: "cPanel", icon: SiCpanel },
  { name: "Figma", icon: SiFigma },
  { name: "Git", icon: SiGit },
  { name: "GitHub", icon: SiGithub },
  { name: "Postman", icon: SiPostman },
  { name: "Google Search", icon: SiGoogle },
  { name: "Google Analytics", icon: SiGoogleanalytics },
  { name: "App Store", icon: SiAppstore },
  { name: "Google Play", icon: SiGoogleplay },
];
