import type { IconType } from "react-icons";
import {
  LuActivity,
  LuArmchair,
  LuBaby,
  LuBookOpen,
  LuBrain,
  LuBriefcase,
  LuBuilding2,
  LuCalculator,
  LuCamera,
  LuCar,
  LuChartLine,
  LuCoffee,
  LuDumbbell,
  LuFlame,
  LuGlobe,
  LuGraduationCap,
  LuHardHat,
  LuHotel,
  LuLanguages,
  LuLeaf,
  LuPartyPopper,
  LuPawPrint,
  LuPlane,
  LuRuler,
  LuScale,
  LuScissors,
  LuShare2,
  LuShirt,
  LuShoppingCart,
  LuSparkles,
  LuStethoscope,
  LuTrendingUp,
  LuTruck,
  LuUserCheck,
  LuUtensils,
  LuWrench,
} from "react-icons/lu";

export const projectSlugs = [
  "iqfinansai",
  "yazici-ticaret",
  "gardossi",
  "uzman-klinik-psikolog",
  "portfolio",
  "onlinemuhasebe",
  "orivis",
  "kargona",
  "leafmint",
  "brewknot",
  "kurviva",
  "lensmark",
  "ironpine",
  "softhearth",
  "loomora",
  "gridvolt",
  "rosethread",
  "inkspire",
  "emlak-ofisi",
  "hukuk-burosu",
  "mimarlik-studyosu",
  "veteriner-klinigi",
  "anaokulu",
  "oto-galeri",
  "insaat-firmasi",
  "kisisel-antrenor",
  "etkinlik-organizasyon",
  "catering-hizmeti",
  "mobilya-atolyesi",
  "teknik-servis",
  "danismanlik-firmasi",
  "saglik-klinigi",
  "yatirim-danismanligi",
  "ceviri-burosu",
  "sosyal-medya-ajansi",
  "ozel-ders-merkezi",
  "restoran-zinciri",
  "saglik-turizmi",
] as const;

export type ProjectSlug = (typeof projectSlugs)[number];

export interface ProjectItemConfig {
  slug: ProjectSlug;
  href?: string;
  titleKey: string;
  descKey: string;
  navDescKey: string;
  icon: IconType;
  external?: boolean;
}

export const projectItems: ProjectItemConfig[] = [
  {
    slug: "iqfinansai",
    href: "/projeler/iqfinansai",
    titleKey: "projectIqfinansTitle",
    descKey: "projectIqfinansDesc",
    navDescKey: "projectIqfinansDesc",
    icon: LuChartLine,
  },
  {
    slug: "yazici-ticaret",
    href: "/projeler/yazici-ticaret",
    titleKey: "projectYaziciTitle",
    descKey: "projectYaziciDesc",
    navDescKey: "projectYaziciDesc",
    icon: LuShoppingCart,
  },
  {
    slug: "gardossi",
    href: "/projeler/gardossi",
    titleKey: "projectGardossiTitle",
    descKey: "projectGardossiDesc",
    navDescKey: "projectGardossiDesc",
    icon: LuArmchair,
  },
  {
    slug: "uzman-klinik-psikolog",
    href: "/projeler/uzman-klinik-psikolog",
    titleKey: "projectUzmanPsikologTitle",
    descKey: "projectUzmanPsikologDesc",
    navDescKey: "projectUzmanPsikologDesc",
    icon: LuBrain,
  },
  {
    slug: "portfolio",
    href: "/projeler/portfolio",
    titleKey: "projectPortfolioTitle",
    descKey: "projectPortfolioDesc",
    navDescKey: "projectPortfolioDesc",
    icon: LuGlobe,
  },
  {
    slug: "onlinemuhasebe",
    href: "/projeler/onlinemuhasebe",
    titleKey: "projectOnlinemuhasebeTitle",
    descKey: "projectOnlinemuhasebeDesc",
    navDescKey: "projectOnlinemuhasebeDesc",
    icon: LuCalculator,
  },
  {
    slug: "orivis",
    titleKey: "projectOrivisTitle",
    descKey: "projectOrivisDesc",
    navDescKey: "projectOrivisDesc",
    icon: LuStethoscope,
    external: true,
  },
  {
    slug: "kargona",
    titleKey: "projectKargonaTitle",
    descKey: "projectKargonaDesc",
    navDescKey: "projectKargonaDesc",
    icon: LuTruck,
    external: true,
  },
  {
    slug: "leafmint",
    titleKey: "projectLeafmintTitle",
    descKey: "projectLeafmintDesc",
    navDescKey: "projectLeafmintDesc",
    icon: LuLeaf,
    external: true,
  },
  {
    slug: "brewknot",
    titleKey: "projectBrewknotTitle",
    descKey: "projectBrewknotDesc",
    navDescKey: "projectBrewknotDesc",
    icon: LuCoffee,
    external: true,
  },
  {
    slug: "kurviva",
    titleKey: "projectKurvivaTitle",
    descKey: "projectKurvivaDesc",
    navDescKey: "projectKurvivaDesc",
    icon: LuGraduationCap,
    external: true,
  },
  {
    slug: "lensmark",
    titleKey: "projectLensmarkTitle",
    descKey: "projectLensmarkDesc",
    navDescKey: "projectLensmarkDesc",
    icon: LuCamera,
    external: true,
  },
  {
    slug: "ironpine",
    titleKey: "projectIronpineTitle",
    descKey: "projectIronpineDesc",
    navDescKey: "projectIronpineDesc",
    icon: LuDumbbell,
    external: true,
  },
  {
    slug: "softhearth",
    titleKey: "projectSofthearthTitle",
    descKey: "projectSofthearthDesc",
    navDescKey: "projectSofthearthDesc",
    icon: LuHotel,
    external: true,
  },
  {
    slug: "loomora",
    titleKey: "projectLoomoraTitle",
    descKey: "projectLoomoraDesc",
    navDescKey: "projectLoomoraDesc",
    icon: LuShirt,
    external: true,
  },
  {
    slug: "gridvolt",
    titleKey: "projectGridvoltTitle",
    descKey: "projectGridvoltDesc",
    navDescKey: "projectGridvoltDesc",
    icon: LuFlame,
    external: true,
  },
  {
    slug: "rosethread",
    titleKey: "projectRosethreadTitle",
    descKey: "projectRosethreadDesc",
    navDescKey: "projectRosethreadDesc",
    icon: LuScissors,
    external: true,
  },
  {
    slug: "inkspire",
    titleKey: "projectInkspireTitle",
    descKey: "projectInkspireDesc",
    navDescKey: "projectInkspireDesc",
    icon: LuSparkles,
    external: true,
  },
  {
    slug: "emlak-ofisi",
    titleKey: "projectEmlakOfisiTitle",
    descKey: "projectEmlakOfisiDesc",
    navDescKey: "projectEmlakOfisiDesc",
    icon: LuBuilding2,
    external: true,
  },
  {
    slug: "hukuk-burosu",
    titleKey: "projectHukukBurosuTitle",
    descKey: "projectHukukBurosuDesc",
    navDescKey: "projectHukukBurosuDesc",
    icon: LuScale,
    external: true,
  },
  {
    slug: "mimarlik-studyosu",
    titleKey: "projectMimarlikStudyosuTitle",
    descKey: "projectMimarlikStudyosuDesc",
    navDescKey: "projectMimarlikStudyosuDesc",
    icon: LuRuler,
    external: true,
  },
  {
    slug: "veteriner-klinigi",
    titleKey: "projectVeterinerKlinigiTitle",
    descKey: "projectVeterinerKlinigiDesc",
    navDescKey: "projectVeterinerKlinigiDesc",
    icon: LuPawPrint,
    external: true,
  },
  {
    slug: "anaokulu",
    titleKey: "projectAnaokuluTitle",
    descKey: "projectAnaokuluDesc",
    navDescKey: "projectAnaokuluDesc",
    icon: LuBaby,
    external: true,
  },
  {
    slug: "oto-galeri",
    titleKey: "projectOtoGaleriTitle",
    descKey: "projectOtoGaleriDesc",
    navDescKey: "projectOtoGaleriDesc",
    icon: LuCar,
    external: true,
  },
  {
    slug: "insaat-firmasi",
    titleKey: "projectInsaatFirmasiTitle",
    descKey: "projectInsaatFirmasiDesc",
    navDescKey: "projectInsaatFirmasiDesc",
    icon: LuHardHat,
    external: true,
  },
  {
    slug: "kisisel-antrenor",
    titleKey: "projectKisiselAntrenorTitle",
    descKey: "projectKisiselAntrenorDesc",
    navDescKey: "projectKisiselAntrenorDesc",
    icon: LuUserCheck,
    external: true,
  },
  {
    slug: "etkinlik-organizasyon",
    titleKey: "projectEtkinlikOrganizasyonTitle",
    descKey: "projectEtkinlikOrganizasyonDesc",
    navDescKey: "projectEtkinlikOrganizasyonDesc",
    icon: LuPartyPopper,
    external: true,
  },
  {
    slug: "catering-hizmeti",
    titleKey: "projectCateringHizmetiTitle",
    descKey: "projectCateringHizmetiDesc",
    navDescKey: "projectCateringHizmetiDesc",
    icon: LuUtensils,
    external: true,
  },
  {
    slug: "mobilya-atolyesi",
    titleKey: "projectMobilyaAtolyesiTitle",
    descKey: "projectMobilyaAtolyesiDesc",
    navDescKey: "projectMobilyaAtolyesiDesc",
    icon: LuArmchair,
    external: true,
  },
  {
    slug: "teknik-servis",
    titleKey: "projectTeknikServisTitle",
    descKey: "projectTeknikServisDesc",
    navDescKey: "projectTeknikServisDesc",
    icon: LuWrench,
    external: true,
  },
  {
    slug: "danismanlik-firmasi",
    titleKey: "projectDanismanlikFirmasiTitle",
    descKey: "projectDanismanlikFirmasiDesc",
    navDescKey: "projectDanismanlikFirmasiDesc",
    icon: LuBriefcase,
    external: true,
  },
  {
    slug: "saglik-klinigi",
    titleKey: "projectSaglikKlinigiTitle",
    descKey: "projectSaglikKlinigiDesc",
    navDescKey: "projectSaglikKlinigiDesc",
    icon: LuActivity,
    external: true,
  },
  {
    slug: "yatirim-danismanligi",
    titleKey: "projectYatirimDanismanligiTitle",
    descKey: "projectYatirimDanismanligiDesc",
    navDescKey: "projectYatirimDanismanligiDesc",
    icon: LuTrendingUp,
    external: true,
  },
  {
    slug: "ceviri-burosu",
    titleKey: "projectCeviriBurosuTitle",
    descKey: "projectCeviriBurosuDesc",
    navDescKey: "projectCeviriBurosuDesc",
    icon: LuLanguages,
    external: true,
  },
  {
    slug: "sosyal-medya-ajansi",
    titleKey: "projectSosyalMedyaAjansiTitle",
    descKey: "projectSosyalMedyaAjansiDesc",
    navDescKey: "projectSosyalMedyaAjansiDesc",
    icon: LuShare2,
    external: true,
  },
  {
    slug: "ozel-ders-merkezi",
    titleKey: "projectOzelDersMerkeziTitle",
    descKey: "projectOzelDersMerkeziDesc",
    navDescKey: "projectOzelDersMerkeziDesc",
    icon: LuBookOpen,
    external: true,
  },
  {
    slug: "restoran-zinciri",
    titleKey: "projectRestoranZinciriTitle",
    descKey: "projectRestoranZinciriDesc",
    navDescKey: "projectRestoranZinciriDesc",
    icon: LuCoffee,
    external: true,
  },
  {
    slug: "saglik-turizmi",
    titleKey: "projectSaglikTurizmiTitle",
    descKey: "projectSaglikTurizmiDesc",
    navDescKey: "projectSaglikTurizmiDesc",
    icon: LuPlane,
    external: true,
  },
];
export function isProjectSlug(slug: string): slug is ProjectSlug {
  return projectSlugs.includes(slug as ProjectSlug);
}

export function hasProjectHref(
  project: ProjectItemConfig,
): project is ProjectItemConfig & { href: string } {
  return Boolean(project.href);
}
