export { ServiceHero } from "./ServiceHero"
export { ServiceFeatures } from "./ServiceFeatures"
export { ServiceProcess } from "./ServiceProcess"
export { ServiceTech } from "./ServiceTech"
export { ServiceProjects } from "./ServiceProjects"
export { ServiceFAQ } from "./ServiceFAQ"
export { ServiceCTA } from "./ServiceCTA"
