import {
  flattenTechCategories,
  seoHizmetleriTechCategories,
  webSitesiTechCategories,
} from "./service-tech-categories";

export const webSitesiPrimaryTech = [
  "Next.js",
  "React",
  "TypeScript",
  "Redux",
  "MySQL",
  "Prisma",
  "Tailwind CSS",
  "Sass & SCSS",
  "Shadcn",
  "Framer Motion",
  "Node.js",
  "REST API",
  "Zustand",
  "Vercel",
  "ixirhost",
  "cPanel",
  "Git",
  "GitHub",
  "Google Analytics",
  "Google Search",
  "Lighthouse",
  "PageSpeed Insights",
  "Postman",
  "PayTR",
] as const;

export const webSitesiYenilemePrimaryTech = flattenTechCategories(
  webSitesiTechCategories,
);

export const uygulamaGelistirmePrimaryTech = [
  "React Native",
  "Expo",
  "TypeScript",
  "Zustand",
  "TanStack Query",
  "Framer Motion",
  "Node.js",
  "REST API",
  "Firebase",
  "PostgreSQL",
  "Prisma",
  "Zod",
  "Vercel",
  "PayTR",
  "App Store",
  "Google Play",
  "Figma",
  "Git",
  "GitHub",
  "Postman",
  "Google Maps",
  "Sentry",
] as const;

export const seoHizmetleriPrimaryTech = flattenTechCategories(
  seoHizmetleriTechCategories,
);

export const teknikDenetimPrimaryTech = [
  "Lighthouse",
  "PageSpeed Insights",
  "Google Search Console",
  "Google Analytics",
  "Next.js",
  "TypeScript",
  "Node.js",
  "Prisma",
  "GitHub",
  "Vercel",
  "Postman",
] as const;

export const bakimVeDestekPrimaryTech = [
  "Next.js",
  "React",
  "TypeScript",
  "Node.js",
  "MySQL",
  "Prisma",
  "PostgreSQL",
  "Vercel",
  "ixirhost",
  "GitHub",
  "Git",
  "Postman",
  "Lighthouse",
  "Upstash",
  "Redis",
] as const;

export const servicePrimaryTechStacks: Partial<
  Record<string, readonly string[]>
> = {
  "web-sitesi-gelistirme": webSitesiPrimaryTech,
  "web-sitesi-yenileme": webSitesiYenilemePrimaryTech,
  "uygulama-gelistirme": uygulamaGelistirmePrimaryTech,
  "seo-hizmetleri": seoHizmetleriPrimaryTech,
  "teknik-denetim": teknikDenetimPrimaryTech,
  "bakim-ve-destek": bakimVeDestekPrimaryTech,
};

export const techIconColors: Record<string, string> = {
  HTML: "text-[#E34F26]",
  CSS: "text-[#1572B6]",
  Redux: "text-[#764ABC]",
  "Google Maps": "text-[#EA4335]",
  JavaScript: "text-[#F7DF1E]",
  TypeScript: "text-[#3178C6]",
  React: "text-[#61DAFB]",
  "Tailwind CSS": "text-[#06B6D4]",
  "Sass & SCSS": "text-[#CC6699]",
  Bootstrap: "text-[#7952B3]",
  Angular: "text-[#DD0031]",
  Vue: "text-[#42B883]",
  "Framer Motion": "text-[#0055FF]",
  Shadcn: "text-[#0A0A0F]",
  "Lightswind UI": "text-[#6366F1]",
  HeroUI: "text-[#0A0A0F]",
  "Headless UI": "text-[#6366F1]",
  HyperUI: "text-[#0A0A0F]",
  "Radix UI": "text-[#161616]",
  mapcn: "text-[#EF4444]",
  NextUI: "text-[#17C964]",
  "Chakra UI": "text-[#319795]",
  "Ant Design": "text-[#0170FE]",
  "TanStack Query": "text-[#FF4154]",
  "Next.js": "text-[#0A0A0F]",
  "Node.js": "text-[#339933]",
  "Express.js": "text-[#0A0A0F]",
  "REST API": "text-brand-accent",
  MySQL: "text-[#00758F]",
  MongoDB: "text-[#47A248]",
  PostgreSQL: "text-[#4169E1]",
  MSSQL: "text-[#CC2927]",
  SQLite: "text-[#003B57]",
  Prisma: "text-[#2D3748]",
  Vercel: "text-[#0A0A0F]",
  Zustand: "text-[#443F43]",
  cPanel: "text-[#FF6C2C]",
  Postman: "text-[#FF6C37]",
  "Google Search": "text-[#4285F4]",
  "Google Search Console": "text-[#458CF5]",
  "Google Analytics": "text-[#E37400]",
  Lighthouse: "text-[#F44B21]",
  "PageSpeed Insights": "text-[#4285F4]",
  Git: "text-[#F05032]",
  GitHub: "text-[#181717]",
  ixirhost: "text-foreground",
  Shopier: "text-foreground/70",
  PayTR: "text-[#FF6C37]",
  iyzico: "text-foreground/70",
  Stripe: "text-[#635BFF]",
  Tools: "text-[#64748B]",
  Flutter: "text-[#02569B]",
  "Android Studio": "text-[#3DDC84]",
  Figma: "text-[#F24E1E]",
  Railway: "text-[#0B0D0E]",
  Render: "text-[#46E3B7]",
  Redis: "text-[#DC382D]",
  Docker: "text-[#2496ED]",
  Upstash: "text-[#00E9A3]",
  Semrush: "text-[#FF642D]",
  "Google Tag Manager": "text-[#246FDB]",
  "JSON-LD": "text-[#6366F1]",
  "App Store": "text-[#0D96F6]",
  "Google Play": "text-[#414141]",
  "Swagger / OpenAPI": "text-[#85EA2D]",
  Kotlin: "text-[#7F52FF]",
  Swift: "text-[#F05138]",
  Firebase: "text-[#DD2C00]",
  Supabase: "text-[#3FCF8E]",
  Sentry: "text-[#362D59]",
  NativeWind: "text-[#06B6D4]",
  Ahrefs: "text-[#FF7A00]",
  Moz: "text-[#008EE2]",
  "Google Looker Studio": "text-[#4285F4]",
  "Meta Pixel": "text-[#0081FB]",
  "Google Trends": "text-[#4285F4]",
  "Screaming Frog SEO Spider": "text-[#84BD00]",
};
